### ISSUE TITLE
About using Telepathy in a Unity-WebGL project

### ISSUE THREAD

**Issue by CommanderLee** [vis2k/Telepathy#111]
Hello,

I am working on a Unity-WebGL project. I have tested Telepathy in the Unity Play Mode, and it worked perfectly.

However, after I built the project, it doesn't work in my web browser. The error message is attached.

![image](https://user-images.githubusercontent.com/4384453/119380159-5907e680-bc8e-11eb-8f41-d57cfc22289a.png)

Do people have some clues on what's happening here? Thank you so much for your time.

Best,
Zhen

**Comment by JesusLuvsYooh** [comment]
You have to use Simple Web Transport, for Webgl  :)   not telepathy
Also webGL cannot be host, they can only join  (so create server as standalone, iphone, PS4 etc)

**Comment by CommanderLee** [comment]
Thank you for your response!
