### ISSUE TITLE
Failed to connect (0x80004005) 

### ISSUE THREAD

**Issue by client** [vis2k/Telepathy#114]
When hosting a server, I am only able to connect to my own local IP address Using a public IP address fails completely. However, port forwarding has already been done, and the port forwarding was tested with a different application. A netstat command shows that the port is in fact listening.

`Client Recv: failed to connect to ip=[my ip here] port=7777 reason=System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

UnityEngine.Debug:Log (object)
NetworkSystem/<>c:<Awake>b2_0 (string) (at Assets/Scripts/NetworkSystem.cs:15)
Telepathy.Client:ReceiveThreadFunction (Telepathy.ClientConnectionState,string,int,int,bool,int,int,int) (at Assets/Imports/Telepathy/Client.cs:156)
Telepathy.Client/<>cDisplayClass14_0:<Connect>b__0 () (at Assets/Imports/Telepathy/Client.cs:240)
System.Threading.ThreadHelper:ThreadStart ()`

**Comment by JesusLuvsYooh** [comment]
https://mirror-networking.gitbook.io/docs/faq#how-to-connect

Two games on same PC
1: localhost works?
2: LAN works?  (192.168.0.x)
3: WAN works?  (google, whats my IP)

If WAN doesnt work with those two games on same pc, then yeah ports or firewalls/anti virus, also try with 2 builds and not Unity editor, sometimes editor likes to be blocked too.

Also try with KCP
If your unblocking ports in router, make sure to set LAN IP of host (192.168.0.x) not wan (a few put wan ip in there)
Telepathy is TCP, KCP is UDP, make sure the right one, or both are unblocked.
