### ISSUE TITLE
Id connection

### ISSUE THREAD

**Issue by erimeurer** [vis2k/Telepathy#120]
When connection is made increasing connection id is created, what happens if this value overflows an int? himself
Does telepathy do any resets?

**Comment by visualbruno** [comment]
> When connection is made increasing connection id is created, what happens if this value overflows an int? himself Does telepathy do any resets?

If I'm not wrong, in C#, when you reach the upper bound of an integer and you increase it, it becomes the lower bound, so -2147483648.

You can try this code:
int iValue = int.MaxValue;
iValue++;

**Comment by MrGadget1024** [comment]
It does not roll over but int.maxValue = 2147483647 so even at one new connection per second it'd take 68 years to exhaust them all.  No server would be up that long.

Close this.
