### ISSUE TITLE
Will support websocket?

### ISSUE THREAD

**Issue by Edisoni** [vis2k/Telepathy#30]
Will support websocket?

**Comment by EdanSmith** [comment]
[Websockets Support](https://github.com/vis2k/Mirror/issues/41)

Hopefully @paulpach will add it in the near future.

**Comment by vis2k** [comment]
Telepathy itself won't, but we will come up with something separate to use for Mirror.
Telepathy will stay small and simple.

**Comment by object71** [comment]
@vis2k If I want to use telepathy separately for a console project. Unity should be able to connect with its telepathy client to the console telepathy server. But this cannot be done for web. Any suggestion on how to approach that case?
