### ISSUE TITLE
Latest version does not work with Mirror

### ISSUE THREAD

**Issue by thevile** [vis2k/Telepathy#41]
Upgrading Telepathy on Mirror causes the transport layer loading to fail on TypeLoadExcpeption.

Steps to reproduce:
1. Create a new project and download Mirror from Asset Store (happens with a local build also).
2. Build the latest version (b2818cb1934ce22bb68548bbe63ec2c04ddd5c0d when writing this) of Telepathy.
3. Copy Telepathy.dll (and Telepathy.pdb) to Assets/Mirror/Plugins and replacing the old files.
4. Run the example scene
5. Following error is given:

```
TypeLoadException: Could not load type 'Mirror.TelepathyTransport' from assembly 'Mirror.Runtime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
Mirror.NetworkManager.InitializeTransport ()
Mirror.NetworkManager.Awake ()
```

**Comment by SoftwareGuy** [comment]
I helped sort (test) this out, I got a NullReferenceException instead when using the NET 3.5 DLLs of a freshly compiled one from the latest commit as seen in [this image](https://media.discordapp.net/attachments/510751218918883348/513993727421710338/unknown.png)

**Comment by vis2k** [comment]
@thevile did you try using the latest Mirror build from the repository? Telepathy is included there and that should work fine.

**Comment by vis2k** [comment]
Mirror now uses the latest Telepathy version and mirror-553 from here: https://github.com/vis2k/Mirror/releases runs just fine for me in Unity + OSX + uMMORPG + build and editor.

**Comment by thevile** [comment]
I needed to do some changes, that is why I was building from source. The issue was as I describe above. Maybe "how to build to build Telepathy for Mirror" guide might be useful for future?

**Comment by vis2k** [comment]
this problem is solved with mirror source drop-in
