### ISSUE TITLE
client disconnect causes server freeze

### ISSUE THREAD

**Issue by paulpach** [vis2k/Telepathy#43]
# Describe the bug
When a client completely shuts off their internet, other users experience a complete drop in server response. The server produces no error logs and in the case that the client reconnects in a timely manner, everything resumes back to normal. This shutting off of the internet is not equivalent to force closing the game, where that still acts like a clean break from the server.

# Desktop (please complete the following information):

* OS: windows and osx
* Build target: standalone and editor
* Unity version: 2018.2

Moving https://github.com/vis2k/Mirror/issues/152  here,  this is a Telepathy issue,  not a Mirror issue

**Comment by paulpach** [comment]
This is being addressed in https://github.com/vis2k/Telepathy/tree/async

**Comment by vis2k** [comment]
fixed a while ago, thanks
