### ISSUE TITLE
Calling Telepathy.Server.Stop() never returns

### ISSUE THREAD

**Issue by NahoyGames** [vis2k/Telepathy#46]
<img width="854" alt="screen shot 2019-01-18 at 6 05 34 pm" src="https://user-images.githubusercontent.com/42898627/51431840-8b4b3a00-1be3-11e9-8e53-eaca6f56a3cf.png">

How to reproduce - Copy the starter code into a new c# visual studio project(and add the main/updates methods, of course). Start the server, "server" as a console application. Call "server.Stop()" with a Console.WriteLine() right after. The Console.WriteLine() won't ever get called, I have to ctrl+c the program to end it. 

```
using System;
using Networking = Telepathy;

class Server
    {
        public static Networking.Server server { get; protected set; }

        public static void Main(string[] args)
        {
            /* START SERVER */
            server = new Networking.Server();
            server.Start(1337);
            Console.WriteLine("Server started!");


            /* UPDATE SERVER */
            while (!(Console.KeyAvailable && Console.ReadKey(true).Key == ConsoleKey.Escape))
            {
                ReceivePackets();
            }


            /* STOP SERVER */
            server.Stop();
            Console.WriteLine("Stopped server");
        }
```

The "ReceivePackets()" method obviously has more stuff, but this issue still occurs even when using the starter code on the readme.

**Comment by vis2k** [comment]
Great find. Fixed here: https://github.com/vis2k/Telepathy/commit/7a13b272d25d46ba7df3809f68e5d5077935343d
