### ISSUE TITLE
ReadSafely ambiguous call in ReadExactly

### ISSUE THREAD

**Issue by Dewskerz** [vis2k/Telepathy#54]
I as able to get a Telepathy test running great as a standalone, but when I move the directory into my Unity project file system I got this error.  Any recommendations on fixing it?

Windows 10, Unity version 2018.3.0f2

![image](https://user-images.githubusercontent.com/16945477/52821339-5eb00400-3063-11e9-8755-a9f2aa39e1e4.png)

**Comment by vis2k** [comment]
did you drop it in as source or as DLL?
maybe the old DLL is still in there?
not sure why it would complain about having that function twice.

**Comment by Dewskerz** [comment]
I think the problem was me including all of the debug/ and obj/ folders when I moved it over to Unity. The problem resolved itself when I got rid of those and stuck with the c# files.

Thanks!

**Comment by Dewskerz** [comment]
I think the problem was me including all of the debug/ and obj/ folders
when I moved it over to Unity. The problem resolved itself when I got rid
of those and stuck with the c# files.

Thanks!

*Andrew Cunningham*
Officer Candidate | E-4 USN
Navy Reserve Officers Training Corps
Paul G. Allen School of Computer Science & Engineering
