### ISSUE TITLE
Which package structures here?

### ISSUE THREAD

**Issue by aloska** [vis2k/Telepathy#56]
Hi. Thanks for your sharing!
Can I know the structure of packages. I mean HEAD END? CRC? 
I just need to connect to my server in C# from GO lang. Thanks.

**Comment by aloska** [comment]
I see you have only Header(4bytes HILO) that represent size of data + Data of this size. Right?
EventType of Connected and Disconnected are from TCP level?
I don't need to sent some for connect or disconnect?

**Comment by paulpach** [comment]
Telepathy has a very minimal format:   4 bytes for message size, and the rest is user provided data.  That is it.

There is no special connect/disconnect message other than tcp connect/disconnection.
