### ISSUE TITLE
README says build is failing.. is this accurate?

### ISSUE THREAD

**Issue by snarlynarwhal** [vis2k/Telepathy#59]
Where should I download the latest stable release of Telepathy from?

**Comment by eriknielsen** [comment]
[This](https://ci.appveyor.com/project/vis2k73562/telepathy/builds/22151729) build a few commits ago passed, I'm not an expert on Telepathy though. If you go to the link and then to the state of the project at that commit, then you can download a building version of the project.

**Comment by snarlynarwhal** [comment]
Got it, thank you!

**Comment by vis2k** [comment]
sorry, we didn't add a build script for releases yet. will do asap.

**Comment by paulpach** [comment]
@vis2k do you want to do semver for Telepathy too?

**Comment by vis2k** [comment]
that would be great

**Comment by Zeejfps** [comment]
@vis2k There is an issue with the ConnectIPv6Test unit test. The loopback address got combined with the ipv4 address somehow lol. It should be "::1"

**Comment by vis2k** [comment]
@Zeejfps what do you mean exactly? which line of code are you talking about?

**Comment by Zeejfps** [comment]
@vis2k sorry I thought this might have been related to an issue i had with connecting to an ipv6 address unit test.
