### ISSUE TITLE
Not supporting ipv6

### ISSUE THREAD

**Issue by insanepure** [vis2k/Telepathy#64]
There is no ipv6 support because of this:
listener = new TcpListener(new IPEndPoint(IPAddress.Any, port));

To fix this, you could do this:

listener = new TcpListener(IPAddress.IPv6Any, port);
listener.Server.SetSocketOption(SocketOptionLevel.IPv6, SocketOptionName.IPv6Only, false);

This would listen to IPv4 and IPv6.

**Comment by vis2k** [comment]
Have you tried it with IPV6 yet?

**Comment by insanepure** [comment]
Just tested it.

So to work you need:

Server.cs
listener = new TcpListener(IPAddress.IPv6Any, port);
listener.Server.SetSocketOption(SocketOptionLevel.IPv6, SocketOptionName.IPv6Only, false);

Client.cs
client = new TcpClient(AddressFamily.InterNetworkV6);


Couldn't test if it works for IPv4 still through.

**Comment by vis2k** [comment]
Fixed, thanks for reporting :)
