### ISSUE TITLE
Server.Send: invalid connectionId: 

### ISSUE THREAD

**Issue by bartofzo** [vis2k/Telepathy#67]
Hi,

Doing some stress testing with sending large amounts of messages (about 250 per second of 10 bytes each) to 16 connected clients and sometimes getting this the Unity console: Server.Send: invalid connectionId: [number]

Doesn't happen when I don't send as much (about 25).

Is this a sign the system can't cope or could there be something else going on?

Thanks

**Comment by GuitoonDev** [comment]
Hi,

I have the same log in the Unity console when I send a message with the example script in the readme.

Each time I send a message when I press the space bar with just one client connected, I have this mesage :
"Server.Send: invalid connectionId: [number]"

How can I fix this ?

Thanks

**Comment by MrGadget1024** [comment]
> 
> 
> Hi,
> 
> I have the same log in the Unity console when I send a message with the example script in the readme.
> 
> Each time I send a message when I press the space bar with just one client connected, I have this mesage :
> "Server.Send: invalid connectionId: [number]"
> 
> How can I fix this ?
> 
> Thanks

There are at least 5 readme files in mirror - tell us which or include the code, or come to Discord for help.
