### ISSUE TITLE
Telepathy hangs itself on Linux x64 hosts

### ISSUE THREAD

**Issue by SoftwareGuy** [vis2k/Telepathy#68]
**Problem:** Telepathy never shuts down the server instance on Linux x64 with NET Core 2.x installed, outputting "Server: Stopping..." and hanging indefinitely.
**Confirmed affected platforms:** Linux
**Confirmed affected versions of Telepathy:** master 
**Can be reproduced?** Yes, with [repro project](https://www.dropbox.com/s/hz9f4v3rm14jkx7/TelepathyHungItself-Repro.zip)

**Bug reproduction instructions**:
Either build the solution in the project archive above or run `dotnet TelepathyHangsItself.dll` in the Build directory. **Do not worry - there is no malicious code**, it simply just runs a thread with the example code in the readme, waits until you press a key and goes home. On Windows, it will exit gracefully, on Linux it hangs after the stopping server message and never says "The bug reproduction project exited successfully".

**Additional thoughts:**
May be related to #46. Regression?

**Comment by SoftwareGuy** [comment]
issue happens both on CentOS 7 Vultr VPS and dedicated server running Ubuntu 18.04 LTS

**Comment by Zeejfps** [comment]
This might be solved using the async method BeginAcceptTcpClient in combination with a ManualResetEvent on the server listening thread. I've forked the repo and will implement the fix when I get home.

**Comment by vis2k** [comment]
sorry, didn't have time for telepathy in a while.
can you confirm that the issue still exists in the latest version?
did a major rewrite in 2021 :)

**Comment by vis2k** [comment]
sorry, didn't have time for telepathy in a while.
major rewrite in 2021 happened.
please see if the bug still exists. if yes, please reopen.
