### ISSUE TITLE
Stopping server causes server to freeze

### ISSUE THREAD

**Issue by allan-m-smith** [vis2k/Telepathy#72]
Hi,

Using telepathy on a C# console application, when creating the most barebones app possible, the application freezes when I try to stop telepathy server.

The code is just this:

```
    class Program
    {
        private static void Main(string[] args)
        {
            Console.WriteLine("Starting Gameplay Server!");

            var server = new Server();
            server.Start(5000);

            Console.WriteLine("Starting server on port [5000]...");

            Thread.Sleep(5000);

            server.Stop();

            Console.WriteLine("Gameplay Server no longer running!");
        }
    }
```

The last line never gets output to the console. This happens when using either the NUGET package or latest revision from this repo. Might be worth noting Im using Visual Studio 2019 for Mac (on a Mac obviously), in case you are unable to reproduce on windows somehow.

You can download this tiny solution here:
https://drive.google.com/open?id=1ktJGU79feAWd8Y8fbAurAMQUFRG9yEOC

Please let me know if there is anything you want me to try out.

Best,
Allan

**Comment by vis2k** [comment]
sorry, didn't have time for telepathy in a while.
major rewrite in 2021 happened.
please see if the bug still exists. if yes, please reopen.

**Comment by allan-m-smith** [comment]
Hi @vis2k!

Thank you for all the work put into Telepathy! I have just updated to the latest master commit (v1.7) and can confirm this issue persists. To be more precise, the code hangs on the listener?.Stop(); call.

Before updating I was using the fix from this pr: https://github.com/vis2k/Telepathy/pull/81

Ill do some digging but unfortunately I'm far from an expert but I'll let you know if I find anything.
