### ISSUE TITLE
Client.Connect blocks code in Unity 2019.2.3f1

### ISSUE THREAD

**Issue by bartofzo** [vis2k/Telepathy#76]
Hi,

Using Telepathy via Mirror. When I connect the client to an IP address that doesn't respond, at first the main thread code will continue to run. But after approx. 5 seconds, the main thread gets blocked for 30 seconds or so... After that the disconnect event is fired and code resumes as normal.

Any idea what causes this? And if this is not fixable, any way to reduce the timeout?

Thanks.

**Comment by PePoDev** [comment]
@bartofzo 
Same problem with this message

> A blocking operation was interrupted by a call to WSACancelBlockingCall

I try example from README and is not working like your case.
When I search around the message, Now I found [THIS](https://stackoverflow.com/questions/31871/wsacancelblockingcall-exception) question about the error message.

I try to move client/server connect/start method to Start/Awake function and it work fine now.
Hope this help you too.

**Comment by PePoDev** [comment]
@bartofzo 
Same problem with this message

> A blocking operation was interrupted by a call to WSACancelBlockingCall

I try example code from README and is not working like your case.
When I search around the message, Now I found [THIS](https://stackoverflow.com/questions/31871/wsacancelblockingcall-exception) question about the error message.

I try to move client/server connect/start method to Start/Awake function and it work fine now.
Hope this help you too.

**Comment by Zeejfps** [comment]
This happens because the listener is closed on a different thread than it was created on. I am submitting a pull request.

**Comment by bartofzo** [comment]
I've seen your solution and I'll try it out tonight. I'll let you know if it fixes it

**Comment by Zeejfps** [comment]
> EDIT:
> 
> Your pull request is about the server but my issue is about a client that connects to an invalid IP address.
> 
> Maybe I've explained the issue wrong. Try connecting to a random IP address that doesn't exist. The code hangs for about 30 seconds.

I see, It's possible the issue might be similar.

**Comment by vis2k** [comment]
sorry, didn't have time for telepathy in a while.
major rewrite in 2021 happened.
please see if the bug still exists. if yes, please reopen.
