### ISSUE TITLE
Exceptions are still thrown each time a player disconnects.

### ISSUE THREAD

**Issue by Davidnovarro** [vis2k/Telepathy#83]
https://github.com/vis2k/Mirror/commit/cb3d9f0d08a961b345ce533d1ce64602f7041e1c
Replacing thread abort with thread interrupt is not a solution to the issue.

Thread.Abort, Thread.Interrupt are intended to be used only in extreme conditions, Telepathy should get rid of them.

1) Exceptions are still thrown.
Exception thrown: 'System.Threading.ThreadInterruptedException' in System.Private.CoreLib.dll

2) Thread.Interrupt is not a graceful way to stop the thread, you should use something like ManualResetEvent to stop the thread and then Thread.Join

[LINK](https://stackoverflow.com/questions/5950994/thread-abort-vs-thread-interrupt)
[LINK](https://social.msdn.microsoft.com/Forums/office/en-US/0c09d11c-2209-41b6-876f-47595d9ed0e5/c-terminate-worker-thread-gracefully?forum=csharpgeneral)
[LINK](https://jonskeet.uk/csharp/threads/shutdown.html)

**Comment by Davidnovarro** [comment]
I've fixed it for myself, here is the solution on how to stop the send thread gracefully with no exceptions.

Instead of using Thread.Interrupt, we just disconnect and wait until the socket is actually disconnected, so we can notify the sendThread to update, the rest will be handled automatically.

In Client.cs find this https://i.imgur.com/8pxyper.png and replace it with this https://pastebin.com/A6YsQVqS
In Server.cs find this https://i.imgur.com/trU4fBJ.png and replace it with this https://pastebin.com/uHFZvd6m

**Comment by Chroma72** [comment]
I added both the fixes but when I do a client.Disconnect() it throws an error saying the client object doesn't exist in Client.cs.

**Comment by vis2k** [comment]
@Davidnovarro thanks for this, I did something similar.
can you please try latest master and see if that works or not? thread is now stopped via manualresetevent.set + thread.join, which should be as good as it gets :)

**Comment by Davidnovarro** [comment]
1) Client Close should be called before updating the send pending.
2) We should wait until the socket is actually disconnected and then only update the send pending.
https://i.imgur.com/OplEWY6.png

And the same thing should be done in Server.cs

**Comment by vis2k** [comment]
thx a lot @Davidnovarro , I completely missed that one. fixed!
