### ISSUE TITLE
Server data never gets received by client

### ISSUE THREAD

**Issue by TheSeanLavery** [vis2k/Telepathy#85]
I'm using Unity 2019.2.19f1

I'm using the unity sample script in the readme.

The connection works fine. 

Sending messages from the client works fine, but the client can't receive messages that are sent by the server.

**Comment by vis2k** [comment]
try the Mirror tanks example in that Unity version and see if you can connect.
if yes, then compare the code

**Comment by vis2k** [comment]
sorry, didn't have time for telepathy in a while.
major rewrite in 2021 happened.
please see if the bug still exists. if yes, please reopen.
