### ISSUE TITLE
client.Disconnect() don't work as expected! ( Infinity loops )

### ISSUE THREAD

**Issue by fdsagizi** [vis2k/Telepathy#86]
Hi guys - i found critical problem! If we try connect to unavailable host like this 185.137.235.2 port 54300

we cannot close **ReceiveThread** after that! Always!
as result we cannot close game - it will freeze infinity 
and Unity Editor will freeze to!

i spend over one day to find the problem!

after try connect to unavailable host, ReceiveThreadFunction will block on **client.Connect(ip, port)**
here: https://github.com/vis2k/Telepathy/blob/d7b78b415cd37843cc7c07b5c805bf43c3a3637f/Telepathy/Client.cs#L54

after that, when we call call **client.Disconnect()** we expect get exception in ReceiveThreadFunction 
like this: **System.Net.Sockets.SocketException (0x80004005): interrupted**

BUT problem is - it never happens! 
As result game or editor will freeze infinity!

After research i found your 'dirty hook':

**client.Client = null;** // clear internal IPv4 socket until Connect()
https://github.com/vis2k/Telepathy/blob/d7b78b415cd37843cc7c07b5c805bf43c3a3637f/Telepathy/Client.cs#L136

as i understand you make it for IpV6 - but as result, you broke **SocketException** 
if remove this code:
**client.Client = null;** // clear internal IPv4 socket until Connect()

all work fine!

and additional - if use **client.Client = null;** we also cannot use async variant of Connect - need timeout for connection!

**client.BeginConnect(ip, port, null, null);**  
it will get null pointer exception - because it required client.Client

**Comment by vis2k** [comment]
sorry, didn't have time for telepathy in a while.
major rewrite in 2021 happened.
please see if the bug still exists. if yes, please reopen.
