### ISSUE TITLE
Question : how to send big data ?

### ISSUE THREAD

**Issue by Fangh** [vis2k/Telepathy#87]
Hello.

I tried to use client.send() with a bytearray so big that it didn't work.
What are your tips to send big data like an image ?

Thank you.

**Comment by vis2k** [comment]
how big?
try modifying maxpacketsize in telepathy.
it can send up to int.max, so around 2 GB if you want it to.

**Comment by Thomas-6freedom** [comment]
I wasn't aware of maxpacketsize.
Thank you.
