### ISSUE TITLE
Broadcast sending

### ISSUE THREAD

**Issue by EdwardNee** [vis2k/Telepathy#89]
Hello, I am new to networking and trying to connect 2 android devices, that are in a one wifi net, using unity. Changed in your sample client.Connect("localhost", 1337); to client.Connect("255.255.255.255", 1337); in order to find server and connect to it, however it does not work. How can I detect all the available servers?
Thanks in advance!

**Comment by uweenukr** [comment]
Did you write 255.255.255.255 for the issue or is that actually the IP you are trying to connect to? Because that is not a valid IP. If you do not already know the IP or you want to scan the network for all available that would be Network Discovery which is outside of the scope of Telepathy itself.
