### ISSUE TITLE
Unable to parse file Assets/Mirror/Runtime/Transport/Telepathy/Telepathy.dll.meta: [Parser Failure at line 30: Expect ':' between key and value within mapping]

### ISSUE THREAD

**Issue by AwesomeAlexx** [vis2k/Telepathy#95]
After upgrading to last asset store version 16.1.1 I got this error (also easch time I clean the library folder) :

Unable to parse file Assets/Mirror/Runtime/Transport/Telepathy/Telepathy.dll.meta: [Parser Failure at line 30: Expect ':' between key and value within mapping]

0x00007FF633309E8C (Unity) StackWalker::GetCurrentCallstack
0x00007FF63330DE41 (Unity) StackWalker::ShowCallstack
0x00007FF631A06225 (Unity) GetStacktrace
0x00007FF633F8947E (Unity) DebugStringToFile
0x00007FF6319DBF2B (Unity) YAMLRead::InitParser
0x00007FF6319D8194 (Unity) YAMLRead::YAMLRead
0x00007FF6310DD563 (Unity) AssetImporter::ReadImportSettings
0x00007FF6310D5517 (Unity) AssetImporter::ApplyImportSettings
0x00007FF631BF5955 (Unity) FindOrProduceImporter
0x00007FF631BFCA0D (Unity) ImportToObjects
0x00007FF631BFC4EE (Unity) ImportAsset
0x00007FF631BFC18B (Unity) AssetImportWorker::Import
0x00007FF631BE2097 (Unity) AssetImportManager::ImportInProcess
0x00007FF631BE12AD (Unity) AssetImportManager::Import
0x00007FF631B7BD28 (Unity) ImportAndPostprocessOutOfDateAssets
0x00007FF631B83B6B (Unity) RefreshInternalV2
0x00007FF631B867E6 (Unity) StopAssetImportingV2
0x00007FF631B7DC16 (Unity) InitialScriptRefreshV2
0x00007FF6310B6192 (Unity) Application::InitializeProject
0x00007FF631A35904 (Unity) WinMain
0x00007FF634A27792 (Unity) __scrt_common_main_seh
0x00007FFC7A587BD4 (KERNEL32) BaseThreadInitThunk
0x00007FFC7C3ECE51 (ntdll) RtlUserThreadStart

**Comment by vis2k** [comment]
use latest telepathy, it doesnt come in a dll anymore
