### ISSUE TITLE
Disconnect is never called!

### ISSUE THREAD

**Issue by PatAPizza56** [vis2k/Telepathy#98]
Hey everyone, I noticed an odd issue. When message is recieved, or the client connects, both of those messages are called. But disconnect is never called! i dont know why this is

**Comment by vis2k** [comment]
sorry, didn't have time for telepathy in a while.
can you confirm that the issue still exists in the latest version?
did a major rewrite in 2021 :)

**Comment by vis2k** [comment]
sorry, didn't have time for telepathy in a while.
major rewrite in 2021 happened.
please see if the bug still exists. if yes, please reopen.

**Comment by PatAPizza56** [comment]
I just implemented the newest version into my project, but I have the same problem. Disconnect is never called
